### ISSUE TITLE
callback plugins have deprecation info

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1109]
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/actionable.py#L17-L20

```
    deprecated:
        why: The 'default' callback plugin now supports this functionality
        removed_in: '2.11'
        alternative: "'default' callback plugin with 'display_skipped_hosts = no' and 'display_ok_hosts = no' options"
```
