### ISSUE TITLE
caddy and ansibullbot roles have unmet group dependency

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1134]
```
    default: TASK [mongodb : Include distribution specific variables] ***********************
    default: ok: [ansibullbot.eng.ansible.com] => (item=/vagrant/playbooks/roles/mongodb/vars/RedHat.yml) => {"ansible_facts": {"mongodb_config_file": "/etc/mongod.conf", "mongodb_data_dir": "/var/lib/mongo", "mongodb_group": "mongod", "mongodb_log_dir": "/var/log/mongodb", "mongodb_log_file": "{{ mongodb_log_dir }}/mongod.log", "mongodb_packages": ["mongodb-org"], "mongodb_pid_file": "/var/run/mongodb/mongod.pid", "mongodb_selinux_ports": "{{ mongodb_port ~ ',' ~ mongodb_shardsvr_port ~ ',' ~ mongodb_configsvr_port ~ ',' ~ mongodb_webstatus_port }}", "mongodb_service_name": "mongod", "mongodb_user": "mongod"}, "ansible_included_var_files": ["/vagrant/playbooks/roles/mongodb/vars/RedHat.yml"], "changed": false, "item": "/vagrant/playbooks/roles/mongodb/vars/RedHat.yml"}
    default: 
    default: TASK [caddy : Include distribution specific variables] *************************
    default: ok: [ansibullbot.eng.ansible.com] => (item=/vagrant/playbooks/roles/caddy/vars/RedHat.yml) => {"ansible_facts": {"caddy_packages": ["caddy"], "caddy_ssl_path": "/etc/pki/tls/caddy"}, "ansible_included_var_files": ["/vagrant/playbooks/roles/caddy/vars/RedHat.yml"], "changed": false, "item": "/vagrant/playbooks/roles/caddy/vars/RedHat.yml"}                                                                                                  
    default: 
    default: TASK [caddy : include] *********************************************************
    default: included: /vagrant/playbooks/roles/caddy/tasks/install-RedHat.yml for ansibullbot.eng.ansible.com
    default: 
    default: TASK [ansibullbot : MONITORING | Add caddy user account to ansibot group] ******
    default: fatal: [ansibullbot.eng.ansible.com]: FAILED! => {"changed": false, "msg": "Group ansibot does not exist"}                                                                                                          
    default:    to retry, use: --limit @/vagrant/playbooks/setup-ansibullbot.retry
    default: 
    default: PLAY RECAP *********************************************************************
    default: ansibullbot.eng.ansible.com : ok=7    changed=0    unreachable=0    failed=1   
    default: success
    default: Warning: ALREADY_ENABLED: 80:tcp
    default: success
```
