### ISSUE TITLE
supershipit is not merging 50786

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1149]
https://github.com/ansible/ansible/pull/50786

**Comment by jctanner** [comment]
````
"automerge_status": "automerge !module file(s) test failed",
```

**Comment by gundalow** [comment]
Hum, well that's confusing.

```yaml
  test/integration/targets/gcp:
    maintainers: $team_google
    supershipit: $team_google
```

Using https://ansibullbot.eng.ansible.com/schemavalidator/

```json
{
  "test/integration/targets/gcp_pubsub_topic/tasks/main.yml": {
    "assign": [
      "erjohnso",
      "rambleraptor"
    ],
    "authors": [
      "googlecloudplatform"
    ],
    "committers": [],
    "deprecated": false,
    "ignore": [
      "supertom"
    ],
    "labels": [
      "ansible",
      "cloud",
      "gcp",
      "google",
      "integration",
      "lib",
      "modules",
      "targets",
      "test"
    ],
    "maintainers": [
      "erjohnso",
      "googlecloudplatform",
      "rambleraptor"
    ],
    "metadata": {},
    "name": "main",
    "namespace": null,
    "namespace_maintainers": [],
    "notify": [
      "erjohnso",
      "googlecloudplatform",
      "rambleraptor"
    ],
    "repo_filename": "test/integration/targets/gcp_pubsub_topic/tasks/main.yml",
    "subtopic": "google",
    "supershipit": [],
    "support": "community",
    "supported_by": "community",
    "topic": "cloud"
  }
}
```

If I delete 
```yaml
  test/integration/targets/gcp:
    maintainers: $team_google
    supershipit: $team_google
```
and retest I get the same, so is there some state not being copied from module lookup to tests path?
