### ISSUE TITLE
Feature: Use BOTMETA for informing about communities

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansibullbot#1153]
So currently @ansibot informs the contributor that there is a Working Group for a small set of WGs, however it would be more flexible if we can get this information directly from BOTMETA.yml.
https://github.com/ansible/ansibullbot/blob/master/ansibullbot/triagers/plugins/community_workgroups.py

If the BOTMETA.yml would have a URL for a label, we could make a generic message for contributors that includes the URL to the communities.

So when something is labeled 'windows' or 'gitlab', it could inform the user about [the Windows WG](https://github.com/ansible/community/wiki/Windows) or [the Gitlab WG](https://github.com/ansible/community/wiki/Gitlab).

This would mean that in BOTMETA.yml there needs to be a mapping between **label** and a **url**. I don't know if we also want to expose a WG name, or if we can keep it generic. Sometimes more labels are being added, so the message could point to one or more Working Groups (e.g. for ZFS we currently also include the Solaris community).

Example config in BOTMETA.yml
```yaml
communities:
  windows:
    name: Windows WG
    url: https://github.com/ansible/community/wiki/Windows
  gitlab:
    name: Gitlab WG
    url: https://github.com/ansible/community/wiki/Gitlab
```
