### ISSUE TITLE
Slug parameter grafana

### ISSUE THREAD

**Issue by LogiEx7** [ansible/ansibullbot#1192]
I try to import grafana dashboard via ansible and i have this error : 
`json file does not contain a meta section with a slug parameter, or you didn't specify the slug parameter.`
This is my ansible code for deploy dashboard:
```
 - name: Import Grafana dashboard foo
  grafana_dashboard:
    grafana_url: http://{{ grafana_ip_addr }}:3000
    grafana_api_key: "{{ grafana_api_key }}"
    state: present
    message: Updated by ansible
    overwrite: yes
    path: "{{ path_file }}/system-dashboard.json" 
```
I'm using ansible 2.5.1 & Grafana v6.1.6.
Has anyone ever had this problem? Or know how to fix it ..
