### ISSUE TITLE
files moved to collection notification/closure

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1255]
If files have been copied/moved to a collection, the bot should: 

A) notify that the collection exists
B) close the PR

A new entry in botmeta could help here and the bot might also query galaxy to find the new location(s).

```yaml
$modules/cloud/gce:
    moved: https://github.com/ansible-collections/ansible_collection_gce
    close: True|False
```
