### ISSUE TITLE
get_url module always raise out "HTTP Error 401: basic auth failed"

### ISSUE THREAD

**Issue by itsgodzilla** [ansible/ansibullbot#1359]
Here is my playbook, when I ran it , it caused 401 error.
( just like the other guy said. Here is his issue: https://groups.google.com/forum/#!topic/ansible-project/AtP7ifLzdjk.)

```
- name: wget rpm 
  get_url:
    url: "http://nginxsrv-file.local/repo/{{ item.src }}"
    dest: "{{ item.dest }}"
    username: 'nginx_sec'
    password: 'A?C$XV/1UhA~vQp%'
  with_items:
    - { src: "jdk.rpm", dest: "/tmp/" }
```

It raised error:
```
{...
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "checksum": "",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "delimiter": null,
            "dest": "/tmp/",
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": null,
            "owner": null,
            "password": "A?C$XV/1UhA~vQp%",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "src": null,
            "timeout": 10,
            "tmp_dest": null,
            "unsafe_writes": null,
            "url": "http://nginxsrv-file.local/repo/jdk.rpm",
            "url_password": "A?C$XV/1UhA~vQp%",
            "url_username": "nginx_sec",
            "use_proxy": true,
            "username": "nginx_sec",
            "validate_certs": true
        }
    },
    "item": {
        "dest": "/tmp/",
        "src": "jdk.rpm"
    },
    "mode": "01777",
    "msg": "Request failed",
    "owner": "root",
    "response": "HTTP Error 401: basic auth failed",
    "size": 4096,
    "state": "directory",
    "status_code": 401,
    "uid": 0,
    "url": "http://nginxsrv-file.local/repo/jdk.rpm"
}
```
Anybody can give help?
