### ISSUE TITLE
Labeling and notifications of PRs that contain tests

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#562]
For searching and notifications of PRs it would be good to mirror the existing functionality of the bot for modules

For PRs that touch `test/integration/targets/FOO/`
* See if `FOO` is a module
* Look up the owner, topic & subtopic
* Apply owner_pr, topic and subtopic labels
* `cc @` the same set of people if this was a module

Repeat for each directory (a PR could update multiple tests for different modules)

**Comment by jctanner** [comment]
This can be done in botmeta now

```
files:
   test/integration/targets:
     labels:
       - test
   test/integration/targets/foo:
     labels:
       - foo 
```
