### ISSUE TITLE
"winrm" component should get a windows label

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#567]
https://github.com/ansible/ansible/issues/25532

**Comment by jctanner** [comment]
@Akasurde were you still working on this?

**Comment by Akasurde** [comment]
I tried but no luck. You can take it.

**Comment by dagwieers** [comment]
I looked at this as well, but it is unclear to me where these component/label-mappings are defined.

**Comment by jctanner** [comment]
This can be implemented as a keyword in botmeta now.

https://github.com/ansible/ansible/blob/devel/.github/BOTMETA.yml#L1008-L1011


For example:
```
  lib/ansible/plugins/connection/winrm.py:
    maintainers: $team_windows_core
    keywords: winrm
    labels:
        - windows
```
