### ISSUE TITLE
$team_azure is not expanding for notification

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#715]
https://github.com/ansible/ansible/pull/20526#issuecomment-323117269

```
cc @$team_azure
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)
<!--- boilerplate: notify --->
```

**Comment by jctanner** [comment]
Looks like a problem with how the entry was made in BOTMETA.yml

```
  contrib/inventory/azure_rm.py:
    keywords:
      - azure azure_rm dynamic inventory script
    maintainers:
       - $team_azure
``

It should have been ...

```
  contrib/inventory/azure_rm.py:
    keywords: azure azure_rm dynamic inventory script
    maintainers: $team_azure
```
