### ISSUE TITLE
Ansibullbot to promote IRC Working groups

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#820]
I wonder if the bot could/should promote the different IRC channels we have.

For example if labels for "azure, aws, network, vmware, windows" then say

> Hi $PERSON, 
> Thank you for the issue/PR, just so you are aware we have dedicated Working Group for $TOPIC.
> You can find other people interested in this in `#ansible-$TOPIC` on Freenode IRC

**Comment by gregdek** [comment]
Oooo. Yespls.

**Comment by gundalow** [comment]
I guess given that the list of Working Groups doesn't change that often we would be OK to hard-coded this. 

Perhaps `BOTMETA.yml` could be extended to contains a mapping of labels to Working Groups (defined as the name of the IRC channel after `#ansible-`) 

```yaml
working_groups:
# mapping from label to working group name
  - aws: aws
  - networking: network #notice difference 
 ... 

```

As well as IRC, I wonder if we should link to the index of the the community page, which in turn has links to to Working Groups agenda, wiki, etc.

**Comment by gundalow** [comment]
This should trigger on issues and PRs.


**Input**

```yaml
working_groups:
# mapping from GitHub label to working group name
  - aws: aws
  - azure: azure
  - jboss: jboss
  - networking: network #notice difference 
  - vmware: vmware
  - windows: windows
 ... 

```


**Triggers**
Given that all working groups already exist as labels in `ansible/ansible` I think we can use the existing labels that Ansibullbot adds. 

This should allow modules, module_utils, inventory scripts, etc to all be processed.


**Outputs**
Add a comment (only once)

> Hi $PERSON, 
> Thank you for the issue/PR, just so you are aware we have dedicated Working Group for $TOPIC.
> You can find other people interested in this in `#ansible-$TOPIC` on Freenode IRC

Maybe skip adding this message if more than one would apply, as it's most likely a large refactor and not relevant.
